version: "3.9"
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: webserver
    container_name: webserver
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
