version: "3.7"
services:
  webserver:
    image: moorara/milad.dev:${VERSION:-latest}
    hostname: webserver
    container_name: webserver
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
